POST http://localhost:3000/api/users
content-type: application/json

{
    "name": "sample3",
    "email": "sample3@gmail.com",
    "password": "123"
}

###

GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/users/643ed61d03686481ab99c2ac

###
PATCH  http://localhost:3000/api/users/
content-type: application/json
Authorization: Bearer
{
    "name": "user2"
}

###
DELETE  http://localhost:3000/api/users/643e9fad0a5d67bfb78f541c

###
POST http://localhost:3000/api/users/login
content-type: application/json

{
    "email": "sample3@gmail.com",
    "password": "123"
}

###
POST http://localhost:3000/api/users/logout
content-type: application/json
Authorization: Bearer